name: arbify
description: >
  A package providing support for internationalizing
  Flutter applications using intl package with Arbify.
version: 0.1.0
homepage: https://github.com/Arbify/arbify_flutter

environment:
  sdk: "3.0.6"

dependencies:
  args: ^2.4.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  intl: ^0.18.0
  intl_utils: ^2.8.4
  path: ^1.8.3
  petitparser: ^5.4.0
  universal_io: ^2.2.2
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.6
  lint: ^2.1.2
  mockito: ^5.4.2
  test: ^1.24.6
